sap.ui.define([
	"sap/ui/base/Object"
], function (Object) {
	"use strict";

	return Object.extend("sap.ui.demo.wt.controller.HelloDialog", {

		_getDialog: function () {
			// create dialog lazily
			if (!this._oDialog) {
				// create dialog via fragment factory
				this._oDialog = sap.ui.xmlfragment("epp.epp.view.EmailDialog", this);
			}
			return this._oDialog;
		},

		open: function (oView) {
			var oDialog = this._getDialog();

			// connect dialog to view (models, lifecycle)
			oView.addDependent(oDialog);

			// open dialog
			oDialog.open();
		},

		onCloseDialog: function () {
			this._getDialog().close();
		},

		/**
		 *@memberOf epp.epp.controller.View1
		 */
		onRequestVoucher: function (oEvent) {
			//This code was generated by the layout editor.
			console.log("OnRequestVoucher");
			var oDialog = this._getDialog();
			var oEntity = this._oDialog.getBindingContext().getObject();
			var mParam = {
				success: function () {
					oDialog.close();
					sap.m.MessageToast.show("Request email has been sent");
				},
				error: function () {}
			};
			var oModel = this._component.getModel();
			oModel.update("/HeaderSet(1)", oEntity, mParam);
			// var oDialog = this._getDialog();
			// oModel.callFunction("/RequestVoucher", {
			// 	method: "GET",
			// 	success: function () {
			// 		oDialog.close();
			// 		sap.m.MessageToast.show("Request email has been sent");
			// 	},
			// 	error: function () {}
			// });
		}
	});

});